version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-it.sh db:5432 -- \
             python manage.py migrate && \
             python manage.py seed && \
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - intranet
    

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    networks:
      - intranet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

networks:
  intranet:
    driver: bridge
