# Generated by Django 5.1.3 on 2024-12-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='delayed_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
